config/routes.rb
# frozen_string_literal: true
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  get '/privacy_policy', to: 'info#privacy_policy', as: :privacy_policy
  get 'for_clubs', to: 'for_clubs#index'
  resources :payments, only: %i[index create]
  resources :catalogs, only: %i[index show]
  resources :registrations
  resources :dogs do
    get :search, on: :collection
    member do
      get :registrations
      post :registrations, to: 'dogs#register'
    end
  end

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get 'signin', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
    get 'signout', to: 'devise/sessions#destroy'
  end
  resources :users, only: %i[new create update destroy] do
    get :update_profile, on: :member
    post :facebook_user_deletion
    get :deletion_status
  end
  get '/update_profile' => 'users#update_profile'
  post '/update_profile' => 'users#update'
  patch '/update_profile' => 'users#update'

  namespace :admin do
    resources :users
    resources :events do
      put :gen_catalog, on: :member
      put :drop_catalog, on: :member
      put :close_registration, on: :member
      put :reopen_registration, on: :member
      put :publish_catalog, on: :member
      put :hide_catalog, on: :member
      resource :catalog, only: %i[show update] do
        get :diploms, on: :member
        get :cards, on: :member
        get :additional_list, on: :member
      end
    end
    resource :catalog, only: :show
    resources :registrations do
      get :payments, on: :collection
    end
    resources :dogs
  end

  resources :breeds, only: :index do
    get :autocomplete_title, on: :collection
    get :autocomplete_colors, on: :collection
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'for_clubs#index'
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  extend Enumerize

  serialize :prices

  has_many :registrations
  has_many :dogs, through: :registrations
  has_many :users, through: :registrations
  has_many :roles, as: :roleable
  belongs_to :club

  has_one_attached :location_map
  has_one_attached :printable_catalog
  has_one_attached :printable_catalog_with_prices
  enumerize :rank, in: %i[universal mono champ], scope: true
  enumerize :catalog_status, in: { missing: 0, processing: 1, done: 5 },
    default: :missing

  scope :future, -> { where 'starts_on > CURRENT_DATE' }
  scope :past, -> { where 'starts_on < CURRENT_DATE' }
  scope :not_past, -> { where 'starts_on >= CURRENT_DATE' }
  scope :opened, -> { where 'registration_closed_at > CURRENT_TIMESTAMP' }

  def universal?
    rank == 'universal'
  end

  def mono?
    !universal?
  end

  def url
    "/events/#{id}"
  end

  def root_event
    Event.where(club_id: club_id, starts_on: starts_on)
         .order(:id)
         .first
  end

  def catalog_published?
    catalog_published_at&.past? && !catalog_hidden_for_all
  end

  def show_full_dogs_data?
    catalog_published?
  end

  def show_classes
    ShowClassesList.call self
  end

  def self.available_for_dog(dog)
    breed_obj = dog.breed_obj
    where(
      'rank = ? OR subject IN(?) OR subject ILIKE(?)',
      :universal,
      [breed_obj.group, breed_obj.alt_group, breed_obj.alt_group_2].flatten,
      "%:#{dog.breed_id},%"
    )
  end
end

app/controllers/admin/events_controller.rb
# frozen_string_literal: true

module Admin
  class EventsController < Admin::ApplicationController
    before_action :set_event, only: %i[
      show edit update destroy printable_catalog drop_catalog
      close_registration reopen_registration
      publish_catalog hide_catalog
    ]

    # GET /events
    def index
      @events = events
        .order(starts_on: :DESC, club_id: :ASC, id: :ASC)
        .includes(:club)
    end

    # GET /events/1
    def show; end

    # GET /events/new
    def new
      @event = Event.new new_event_params
    end

    # GET /events/1/edit
    def edit; end

    # POST /events
    def create
      @event = Event.new(event_params)

      if @event.save
        if params[:copy]
          attrs = @event.attributes.except('id')
          redirect_to new_admin_event_path(event: attrs)
        else
          redirect_to admin_events_path, notice: 'Event was successfully created.'
        end
      else
        render :new
      end
    end

    # PATCH/PUT /events/1
    def update
      if @event.update(event_params)
        if params[:copy]
          attrs = @event.attributes.except('id')
          redirect_to new_admin_event_path(event: attrs)
        else
          render :edit
        end
      else
        render :edit
      end
    end

    # DELETE /events/1
    def destroy
      @event.destroy
      redirect_to events_url, notice: 'Event was successfully destroyed.'
    end

    def printable_catalog
      send_file @event.printable_catalog.path
    end

    def gen_catalog
      GenerateCatalogJob.perform_async(
        params[:id], params[:prices].present?
      )

      redirect_to admin_events_path
    end

    def drop_catalog
      Registration.where(event_id: params[:id]).update_all catalog_number: nil
      @event.update catalog_status: :missing

      redirect_to admin_events_path
    end

    def close_registration
      @event.update registration_closed_at: Time.zone.now

      redirect_to admin_events_path
    end

    def reopen_registration
      @event.update registration_closed_at: Time.zone.now + 1.day

      redirect_to admin_events_path
    end

    def publish_catalog
      @event.update(
        catalog_published_at: Time.zone.now,
        catalog_hidden_for_all: false
      )

      redirect_to admin_events_path
    end

    def hide_catalog
      @event.update(
        catalog_hidden_for_all: true
      )
      
      redirect_to admin_events_path
    end

    private

    def init_prices
      {
        (Date.today + 1.week).to_s => {
          baby: baby_prices,
          open: open_prices
        }
      }
    end

    def baby_prices
      { by: { value: 35, currency: :BYN }, www: { value: 35, currecy: :RUB } }
    end

    def open_prices
      { by: { value: 40, currency: :BYN }, www: { value: 40, currecy: :RUB } }
    end

    def events
      scope = Event.all
      return scope if current_user.superadmin?

      Event.where(id: current_user.adminable_event_ids)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = events.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def event_params
      params.require(:event).permit(
        :name, :short_name, :starts_on, :rank, :subject,
        :catalog_published_at, :registration_closed_at,
        :address, :location, :location_map, :club_id, prices: {}
      )
    end

    def opt_event_params
      params.fetch(:event).permit(
        :name, :short_name, :starts_on, :rank, :subject,
        :catalog_published_at, :registration_closed_at,
        :address, :location, :location_map, :club_id, prices: {}
      )
    end

    def new_event_params
      if params[:event]
        opt_event_params
      else
        { prices: Event.last&.prices }
      end
    end
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]

  # GET /events
  def index
    @events = Event.all
  end

  # GET /events/1
  def show; end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit; end

  # POST /events
  def create
    @event = Event.new(event_params)

    if @event.save
      redirect_to @event, notice: 'Event was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /events/1
  def update
    if @event.update(event_params)
      redirect_to @event, notice: 'Event was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /events/1
  def destroy
    @event.destroy
    redirect_to events_url, notice: 'Event was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def event_params
    params.require(:event).permit(:name, :short_name, :starts_on, :rank)
  end
end

app/views/admin/events/_form.html.slim
= form_for [:admin, @event], multipart: true,
    html: { class: "form form-horizontal event" } do |f|
  .form-group
    = f.label :club, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.select :club_id, current_user.adminable_clubs.map { |i| [i.name, i.id] }, class: 'form-control'
    = f.error_span(:rank)
  .form-group
    = f.label :name, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :name, :class => 'form-control'
    = f.error_span(:name)
  .form-group
    = f.label :short_name, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :short_name, :class => 'form-control'
    = f.error_span(:short_name)
  .form-group
    = f.label :starts_on, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.date_field :starts_on, :class => 'form-control'
    = f.error_span(:starts_on)
  .form-group
    = f.label :rank, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.select :rank, Event.rank.values, class: 'form-control'
    = f.error_span(:rank)
  .form-group
    = f.label :subject, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :subject, :class => 'form-control'
    = f.error_span(:subject)
  .form-group
    = f.label :catalog_published_at, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.datetime_local_field :catalog_published_at, :class => 'form-control'
    = f.error_span(:catalog_published_at)
  .form-group
    = f.label :registration_closed_at, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.datetime_local_field :registration_closed_at, :class => 'form-control'
    = f.error_span(:registration_closed_at)
  .form-group
    = f.label :address, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :address, class: 'form-control'
    = f.error_span(:address)
  .form-group
    = f.label :location, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :location, class: 'form-control'
    = f.error_span(:location)
  .form-group
    = f.label :location_map, class: 'control-label col-lg-2'
    .col-lg-10
      = f.file_field :location_map, class: 'form-control'
    = f.error_span(:location_map)

  .form-group
    = f.label :prices, :class => 'control-label col-lg-2'
    .col-lg-10
      = react_component 'Event/Prices', prices: @event.prices || {}, default_date: @event.starts_on, show_classes: @event.show_classes
    = f.error_span(:prices)
    br
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil, :class => 'btn btn-primary'
      = f.submit t('save_and_copy'), :class => 'btn btn-primary', name: :copy
      '
      = link_to t('.cancel', :default => t("helpers.links.cancel")), admin_events_path, :class => 'btn'

app/views/admin/events/edit.html.slim
- model_class = Event
.page-header
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/admin/events/index.html.slim
- model_class = Event
.d-flex.justify-content-between.align-items-start
  h1=t '.title'
  = link_to t('.new', :default => t("helpers.links.new")), new_admin_event_path, :class => 'btn btn-primary'
table.table.table-striped.admin_events
  thead
    tr
      th= model_class.human_attribute_name(:starts_on)
      th= model_class.human_attribute_name(:short_name)
      th= model_class.human_attribute_name(:catalog)
      th
  tbody
    - @events.each do |event|
      tr
        td= event.starts_on
        td
          small
            = event.club.name
          div
            strong
              = link_to event.short_name, edit_admin_event_path(event)
        td
          - if event.catalog_status.missing?
            = link_to 'Gen Catalog', gen_catalog_admin_event_path(event), method: :put
          - elsif event.catalog_status.processing?
            | processing
          - elsif event.catalog_status.done?
            - if event.printable_catalog.attached?
              = link_to url_for(event.printable_catalog) do
                | каталог.docx
              | &nbsp;
              = link_to drop_catalog_admin_event_path(event), method: :put do
                i.bi-trash
            - else 
              | Catalog error
            br
            = link_to 'Gen Prices', gen_catalog_admin_event_path(event, prices: true), method: :put
        td.actions.text-center
          - if event.catalog_published?
            = link_to hide_catalog_admin_event_path(event), method: :put do
              i.bi-eye-slash-fill
          - else
            = link_to publish_catalog_admin_event_path(event), method: :put do
              i.bi-eye-fill
          '  
          - if event.registration_closed_at&.future?
            = link_to close_registration_admin_event_path(event), method: :put do
              i.bi-calendar-x.text-danger
          - else
            = link_to reopen_registration_admin_event_path(event), method: :put do
              i.bi-calendar-plus

          - if false
            = link_to t('.edit', :default => t("helpers.links.edit")), edit_event_path(event), :class => 'btn btn-default btn-xs'
            '
            = link_to t('.destroy', :default => t("helpers.links.destroy")), event_path(event), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

app/views/admin/events/new.html.slim
- model_class = Event
.page-header
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/admin/events/show.html.slim
- model_class = Event
.page-header
  h1=t '.title', :default => model_class.model_name.human.titleize

p
  strong= model_class.human_attribute_name(:name) + ':'
  br
  == @event.name
p
  strong= model_class.human_attribute_name(:short_name) + ':'
  br
  = @event.short_name
p
  strong= model_class.human_attribute_name(:starts_on) + ':'
  br
  = @event.starts_on
p
  strong= model_class.human_attribute_name(:rank) + ':'
  br
  = @event.rank

= link_to t('.back', :default => t("helpers.links.back")), events_path, :class => 'btn btn-default'
'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_event_path(@event), :class => 'btn btn-default'
'
= link_to t('.destroy', :default => t("helpers.links.destroy")), event_path(@event), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'