config/routes.rb
# frozen_string_literal: true
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  get '/privacy_policy', to: 'info#privacy_policy', as: :privacy_policy
  get 'for_clubs', to: 'for_clubs#index'
  resources :payments, only: %i[index create]
  resources :catalogs, only: %i[index show]
  resources :registrations
  resources :dogs do
    get :search, on: :collection
    member do
      get :registrations
      post :registrations, to: 'dogs#register'
    end
  end

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get 'signin', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
    get 'signout', to: 'devise/sessions#destroy'
  end
  resources :users, only: %i[new create update destroy] do
    get :update_profile, on: :member
    post :facebook_user_deletion
    get :deletion_status
  end
  get '/update_profile' => 'users#update_profile'
  post '/update_profile' => 'users#update'
  patch '/update_profile' => 'users#update'

  namespace :admin do
    resources :users
    resources :events do
      put :gen_catalog, on: :member
      put :drop_catalog, on: :member
      put :close_registration, on: :member
      put :reopen_registration, on: :member
      put :publish_catalog, on: :member
      put :hide_catalog, on: :member
      resource :catalog, only: %i[show update] do
        get :diploms, on: :member
        get :cards, on: :member
        get :additional_list, on: :member
      end
    end
    resource :catalog, only: :show
    resources :registrations do
      get :payments, on: :collection
    end
    resources :dogs
  end

  resources :breeds, only: :index do
    get :autocomplete_title, on: :collection
    get :autocomplete_colors, on: :collection
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'for_clubs#index'
end

app/models/dog.rb
# frozen_string_literal: true

class Dog < ApplicationRecord
  include ActiveModel::Serializers::JSON
  extend Enumerize

  DOCUMENT_ALTERNATIVES = %i[puppy_card exchange].freeze

  has_one_attached :doc_img

  has_many :registrations
  has_many :events, through: :registrations
  belongs_to :user, optional: true

  # validates :doc_img, attached: true, if: :document_is_pedigree?
  validates :name, uniqueness:
    { scope: %i[breed_id date_of_birth user_id], message: :not_uniq }

  validates :breed_id, inclusion: { in: Breed.keys.map(&:to_s) }

  validates :name, :document, :owner, :sex, :breeder,
            :mother_name, :father_name, presence: true

  validates :color_str, presence: true, unless: :color_id
  validates :color_id, presence: true, unless: :color_str

  before_validation :normalize_color

  validate :date_of_birth_in_the_past
  validate :hair_type_right_value
  validate :color_id_right_value

  scope :available_sexes, -> { sex.values | group(:sex).pluck(:sex) }

  enumerize :sex, in: %i[male female], scope: true

  strip_attributes collapse_spaces: true, replace_newlines: true

  def url
    "/dogs/#{id}"
  end

  def breed
    return if breed_id.blank?

    I18n.t("breeds.#{breed_id}")
  end

  def date_of_birth_in_the_past
    return if date_of_birth.present? && date_of_birth.past?

    errors.add :date_of_birth, :wrong
  end

  def hair_type_right_value
    return if breed.blank?

    if breed_obj.hair_types.blank?
      self.hair_type_id = nil
      return
    end
    return if hair_type_id.to_s.in? breed_obj.hair_type_ids

    errors.add :hair_type_id, :wrong
  end

  def color_id_right_value
    return if breed.blank?
    return if breed_obj.colors.blank?
    return if color_id.to_s.in? breed_obj.color_ids

    errors.add :color_id, :wrong
  end

  def color
    if color_id.blank?
      return unless color_str

      if I18n.exists? "colors.#{color_str}"
        I18n.t "colors.#{color_str}"
      else
        color_str
      end
    else
      I18n.t("colors.#{color_id}")
    end
  end

  def hair_type
    return if hair_type_id.blank?

    I18n.t("hair_types.#{hair_type_id}")
  end

  def breed_obj
    return if breed_id.blank?

    Breed.find breed_id
  end

  def opened_registrations
    registrations.joins(:event).merge(Event.not_past)
  end

  def color_str=(value)
    super value&.mb_chars&.downcase
  end

  def name=(value)
    super value&.mb_chars&.titleize
  end

  def normalize_color
    return self.color_str = nil if color_id.present?
    return if color_str.blank?

    formatted_val = color_str&.mb_chars&.downcase.to_s.strip
    color_id = I18n.t('colors').key(formatted_val)
    if color_id.present?
      self.color_id = color_id
      self.color_str = nil
    else
      self.color_str = formatted_val
    end
  end

  def mother_name=(value)
    super value&.mb_chars&.titleize
  end

  def father_name=(value)
    super value&.mb_chars&.titleize
  end

  def breeder=(value)
    super value&.mb_chars&.titleize
  end

  def owner=(value)
    super value&.mb_chars&.titleize
  end

  def color_group_id
    breed_obj.color_group(color_id)
  end

  def human_color_group
    return '' unless color_id

    group_key = "color_groups.#{breed_obj.color_group(color_id)}"
    return I18n.t group_key if I18n.exists? group_key

    I18n.t "colors.#{color_id}"
  end

  def human_hair_type
    return '' unless hair_type_id

    key = "hair_types.#{hair_type_id}"
    I18n.exists?(key) ? I18n.t(key) : ''
  end

  def male?
    sex.to_sym == :male
  end

  def female?
    !male?
  end

  def gender
    sex
  end

  def age
    return unless date_of_birth

    count = ((Date.today - date_of_birth) / 365 * 12).round
    if count < 24
      key = 'x_months'
    else
      count /= 12
      key = 'x_years'
    end

    I18n.t("datetime.distance_in_words.#{key}", count: count)
  end

  def document_is_pedigree?
    return false if document.blank?

    !document.to_sym.in? DOCUMENT_ALTERNATIVES
  end

  def human_document
    return document if document_is_pedigree?

    I18n.t("dogs.document_alts.#{document}")
  end

  def to_json
    DogSerializer.new(self).to_json
  end
end

app/controllers/admin/dogs_controller.rb
# frozen_string_literal: true

module Admin
  class DogsController < Admin::ApplicationController
    before_action :set_dog, only: %i[show edit update destroy]

    # GET /dogs
    def index
      @dogs = Dog.all
      @dogs = @dogs.where('color_id IS NULL OR breed_id IS NULL') if params[:not_success]
      @dogs = @dogs.limit(20)

      respond_to do |format|
        format.html
        format.json { render json: @dogs.to_json }
      end
    end

    # GET /dogs/1
    def show; end

    # GET /dogs/new
    def new
      @dog = Dog.new
    end

    # GET /dogs/1/edit
    def edit; end

    # POST /dogs
    def create
      @dog = @current_user.dogs.build(dog_params)

      if @dog.save
        render json: @dog.to_json
      else
        render status: 400, json: { errors: @dog.errors }
      end
    end

    # PATCH/PUT /dogs/1
    def update
      if @dog.update(dog_params)
        render json: @dog.to_json
      else
        render status: 400, json: { errors: @dog.errors }
      end
    end

    # DELETE /dogs/1
    def destroy
      @dog.destroy

      head :ok
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_dog
      dogs = if current_user.superadmin?
          Dog
        else
          Dog.joins(:registrations)
            .where registrations: { event_id: current_user.adminable_event_ids }
        end
      @dog = dogs.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def dog_params
      params
        .require(:dog)
        .permit(:breed, :breed_id, :name, :color_str, :color_id, :document, :doc_img,
                :date_of_birth, :hair_type, :hair_type_id, :sex, :breeder,
                :owner, :mother_name, :father_name, :titles, :chip, :stigma)
        .except :breed, :color, :hair_type
    end
  end
end

app/controllers/dogs_controller.rb
# frozen_string_literal: true

class DogsController < ApplicationController
  before_action :set_dog,
                only: %i[show edit update destroy registrations register]
  before_action :check_user_has_a_dog, except: %i[new create update]
  respond_to :json, only: %i[create update]

  # GET /dogs
  def index
    @dogs = @current_user.dogs
    @registrations = fetch_registrations

    respond_to do |format|
      format.html
      format.json { render json: @dogs.to_json }
    end
  end

  def search
    filtered_dogs = Dog.where('name ILIKE ?', "#{params[:search]}%")
      .order("user_id = #{current_user.id} DESC, created_at DESC")
    @dogs = Dog.select('DISTINCT ON (name) *').from(filtered_dogs).limit 10

    render json: @dogs.to_json
  end

  # GET /dogs/new
  def new
    @dog = Dog.new
  end

  # POST /dogs
  def create
    @dog = @current_user.dogs.build(dog_params)

    render_json_dog_or_errors @dog.save
  end

  # PATCH/PUT /dogs/1
  def update
    render_json_dog_or_errors @dog.update(dog_params)
  end

  # DELETE /dogs/1
  def destroy
    @dog.destroy
    redirect_to dogs_url, notice: 'Dog was successfully destroyed.'
  end

  def registrations
    respond_to do |format|
      format.html do
        available_events_empty_notice
        render
      end
      format.json do
        @registrations = all_available_registations
        @clubs = all_available_events.map(&:club).uniq
        @events = all_available_events.uniq
      end
    end
  end

  def register
    @registration = @current_user.registrations.build(registration_params)
    if @registration.save
      render json: @registration.to_json, status: 201
    else
      render json: @registration.errors.to_json, status: 400
    end
  end

  private

  def fetch_registrations
    Registration.joins(:event)
      .merge(params[:show_all] ? Event.all : Event.not_past)
      .to_a
      .group_by(&:dog_id)
  end

  def render_json_dog_or_errors(result)
    if result
      render json: @dog.to_json
    else
      render status: 400, json: { errors: @dog.errors }
    end
  end

  def available_events_empty_notice
    return if available_events.any?

    flash[:error] = I18n.t('registrations.has_no_available')
  end

  def check_user_has_a_dog
    return if current_user.privileged?
    return if current_user.dogs.any?

    redirect_to new_dog_path
  end

  def registration_params
    params.require(:registration).permit(:show_class, :dog_id, :event_id, :user_id, :note, :paper_wanted)
  end

  def available_events
    Event.not_past.opened.available_for_dog @dog
  end

  def all_available_events
    available_events + @dog.events.not_past
  end

  def all_available_registations
    all_available_events
      .uniq
      .sort_by { |event| [event.starts_on, event.club_id] }
      .map { |event| fetch_registration event }
  end

  def fetch_registration(event)
    event.registrations.find_by(dog_id: @dog.id) ||
      event.registrations.build(dog: @dog, paper_wanted: nil)
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_dog
    dogs = current_user.superadmin? ? Dog : current_user.dogs

    @dog = dogs.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def dog_params
    params
      .require(:dog)
      .permit(:breed, :breed_id, :name, :color_str, :color_id, :document, :doc_img,
              :date_of_birth, :hair_type, :hair_type_id, :sex, :breeder,
              :owner, :mother_name, :father_name, :titles, :chip, :stigma)
      .except :breed, :color, :hair_type
  end
end

app/views/dogs/_dog.slim
.card.mb-3
  .card-body.pb-1
    h5.card-title.mb-0
      = link_to edit_dog_path(dog), class: 'dog-title' do
        = dog.name.mb_chars.titleize
    p.card-text = dog.breed.mb_chars.titleize
  - registrations = @registrations[dog.id]
  - if registrations.present?
    ul.list-group.list-group-flush
      = render partial: 'registration', collection: registrations

- if false
  .row.dog.pb-3
    figure.mb-0
      blockquote.blockquote.text-truncate
      figcaption.blockquote-footer.dog-breed.mb-0 = dog.breed
    - if dog.opened_registrations.any?
      .container
        .row
          .col-sm-12.col-md-6.col-lg-4.col-xl-4.dog-registrations
            = render partial: 'registration', collection: dog.opened_registrations

app/views/dogs/_form.html.slim
coffee:
  window.redirectToRegistrationsAfterSaveDog = (dog) =>
    url = "/dogs/" + dog.id + "/registrations"
    console.log(url)
    window.location.href = url

= react_component 'dog/Form/index',
    dog: @dog.persisted? ? DogSerializer.new(@dog).as_json : { name: '' },
    current_user: current_user.attributes.merge(initials: current_user.initials),
    submitButtonTitle: I18n.t(@dog.persisted? ? 'save' : 'next'),
    submitButtonNote: I18n.t("dog.#{@dog.persisted? ? 'and_go_to_events' : 'go_to_events'}"),
    onSave: 'redirectToRegistrationsAfterSaveDog',
    disabled: @dog.registrations.joins(:event).merge(Event.future).where.not(catalog_number: nil).any?

app/views/dogs/_registration.slim
- event = registration.event
li.list-group-item.d-flex.justify-content-between
  .event
    .fa.fa-trophy
    - if false
      == event.club.name.titleize
    a.ms-2.link-secondary href=event.url
      == event.name
  .details
    span.show-class
      small.text-muted
        = "#{Registration.human_attribute_name :show_class}: "
      = registration.show_class_text.downcase
    - if registration.event.catalog_published_at&.past? 
      - if registration.catalog_number
        = link_to catalog_path(registration.event_id, anchor: "reg#{registration.id}")
          strong.catalog_number.ms-2
            | ##{registration.catalog_number}

- if false
  .row.dog-registration
    .col-6
      span.event-title.link-secondary.text-truncate title=event.starts_on data-bs-toggle="popover" data-bs-content="event.name" data-bs-trigger="hover focus"
        = event.short_name
      a.col-6.event-title.link-secondary href=event.url
        .fa.fa-info
    .col-6.registration.text-end
      small.text-muted
        = "#{Registration.human_attribute_name :show_class}: "
      = registration.show_class_text.downcase

app/views/dogs/edit.html.slim
- model_class = Dog
.page-header
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/dogs/index.html.slim
- model_class = Dog
.page-header.d-flex.justify-content-between
  h1=t '.title'
  .new-dog-link.align-self-center
    = link_to new_dog_path do
      .fas.fa-plus.fa-xs
      |  #{t '.new_dog'}
      - # .fas.fa-dog

.list-options.d-flex.justify-content-end.fst-italic.my-2
  small
    - if params[:show_all]
      = link_to t('.show_active'), dogs_path, id: :show_active
    - else
      = link_to t('.show_past_too'), dogs_path(show_all: true), id: :show_all
.dog-list
= render partial: 'dog', collection: @dogs

app/views/dogs/new.html.slim
- model_class = Dog
.page-header
  h1=t '.title'
-#  react_component('Dog', { name: 'Бобик' })
= render partial: 'form'

app/views/dogs/registrations.html.slim
h1= t '.title'
h3= @dog.name
= react_component('dog/Registrations', dog: @dog.attributes)

app/views/dogs/show.html.slim
.row
  .col
    = link_to t('.back', :default => t("helpers.links.back")), dogs_path, :class => 'btn btn-default'
.row
  .col-sm-2
    - model_class = Dog
    .page-header
      h1=t '.title', :default => model_class.model_name.human.titleize

    p
      strong= model_class.human_attribute_name(:breed) + ':'
      br
      = @dog.breed
    p
      strong= model_class.human_attribute_name(:breed_str) + ':'
      br
      = @dog.breed_str
    p
      strong= model_class.human_attribute_name(:name) + ':'
      br
      = @dog.name
    p
      strong= model_class.human_attribute_name(:color) + ':'
      br
      = @dog.color
    p
      strong= model_class.human_attribute_name(:sex) + ':'
      br
      = @dog.sex
    p
      strong= model_class.human_attribute_name(:document) + ':'
      br
      = @dog.document
    p
      strong= model_class.human_attribute_name(:date_of_birth) + ':'
      br
      = @dog.date_of_birth
    p
      strong= model_class.human_attribute_name(:breeder) + ':'
      br
      = @dog.breeder
    p
      strong= model_class.human_attribute_name(:owner) + ':'
      br
      = @dog.owner
    p
      strong= model_class.human_attribute_name(:mother_name) + ':'
      br
      = @dog.mother_name
    p
      strong= model_class.human_attribute_name(:father_name) + ':'
      br
      = @dog.father_name

    '
    = link_to t('.edit', :default => t("helpers.links.edit")), edit_dog_path(@dog), :class => 'btn btn-default'
    '
    = link_to t('.destroy', :default => t("helpers.links.destroy")), dog_path(@dog), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

  .col-sm-7
    .document-preview
    = form_for @dog, remote: true, html: { multipart: true, remote: true} do |f|
      = f.file_field :doc_img, direct_upload: true
      = f.submit

    = react_component('Dog', @dog.attributes)
    - # Event
    - dog = @dog
    .ul.list-group
      - Event.future.each do |event|
        - next if event.subject.present? && (event.subject != dog.breed_obj.group && event.subject != dog.breed_id)
        - registration = Registration.find_by(event_id: event.id, dog_id: dog.id)
        - registration ||= Registration.new(event: event, dog: dog, user: dog.user)
        li.list-group-item.event.p-5
          h2.display-1.text-center== event.name
          = render 'registrations/catalog_item', registration: registration
          br
          br
          br