config/routes.rb
# frozen_string_literal: true
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  get '/privacy_policy', to: 'info#privacy_policy', as: :privacy_policy
  get 'for_clubs', to: 'for_clubs#index'
  resources :payments, only: %i[index create]
  resources :catalogs, only: %i[index show]
  resources :registrations
  resources :dogs do
    get :search, on: :collection
    member do
      get :registrations
      post :registrations, to: 'dogs#register'
    end
  end

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get 'signin', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
    get 'signout', to: 'devise/sessions#destroy'
  end
  resources :users, only: %i[new create update destroy] do
    get :update_profile, on: :member
    post :facebook_user_deletion
    get :deletion_status
  end
  get '/update_profile' => 'users#update_profile'
  post '/update_profile' => 'users#update'
  patch '/update_profile' => 'users#update'

  namespace :admin do
    resources :users
    resources :events do
      put :gen_catalog, on: :member
      put :drop_catalog, on: :member
      put :close_registration, on: :member
      put :reopen_registration, on: :member
      put :publish_catalog, on: :member
      put :hide_catalog, on: :member
      resource :catalog, only: %i[show update] do
        get :diploms, on: :member
        get :cards, on: :member
        get :additional_list, on: :member
      end
    end
    resource :catalog, only: :show
    resources :registrations do
      get :payments, on: :collection
    end
    resources :dogs
  end

  resources :breeds, only: :index do
    get :autocomplete_title, on: :collection
    get :autocomplete_colors, on: :collection
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'for_clubs#index'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable,
         # :validatable,
         # :confirmable,
         :lockable, :trackable, :masqueradable,
         :omniauthable, omniauth_providers: %i[google_oauth2 facebook vkontakte]
  has_many :dogs
  has_many :registrations

  has_many :roles
  has_many :roleable_clubs, class_name: 'Club',
                            through: :roles, source: :roleable, source_type: 'Club'
  has_many :roleable_events, class_name: 'Event',
                             through: :roles, source: :roleable, source_type: 'Event'
  has_many :payments

  # has_many :adminable_clubs,

  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates :phone, phone_number: true, allow_blank: false
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :password, presence: true, on: :create
  validates :password, confirmation: true,
                       unless: -> { password.blank? }, on: :create

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.find_by email: data['email']
    user || create_from_omniauth(data)
  end

  def adminable_clubs
    return Club.all if superadmin?

    roleable_clubs
  end

  def adminable_event_ids
    return Event.all.pluck(:id) if superadmin?
    [adminable_clubs_event_ids + roleable_event_ids].flatten.uniq
  end

  def adminable_events
    Event.where id: adminable_event_ids
  end

  def adminable_clubs_event_ids
    Event.where(club_id: roleable_club_ids).pluck(:id)
  end

  def phone=(value)
    super Phoner::Phone.parse(value).to_s
  rescue StandardError
    super value
  end

  def fullname
    [last_name, first_name, second_name].compact * ' '
  end

  def initials
    return if last_name.blank?

    name_part = "#{first_name[0]&.capitalize}."
    second_name_part = second_name.present? ? "#{second_name[0]&.capitalize}." : nil
    ([last_name, name_part, second_name_part].compact * ' ')
      .gsub(/\b('?\W)/) { Regexp.last_match(1).capitalize }
  end

  def superadmin?
    # email == 'ilp416@gmail.com'
    name == 'superadmin'
  end

  def privileged?
    superadmin? || roles.any?
  end

  def self.create_from_omniauth(data)
    my_logger = Logger.new("#{Rails.root}/log/oauth.log")
    my_logger.info("Creating user with data: #{data}")
    user = User.new(
      name: data[:name],
      first_name: data[:first_name],
      last_name: data[:last_name],
      email: data[:email],
      password: Devise.friendly_token[0, 20],
      avatar: data[:image],
      confirmed_at: data[:email_verified] == false ? nil : Time.zone.now
    )
    user.save validate: false
    user
  end
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

module Admin
  class UsersController < Admin::ApplicationController
    before_action :set_user, only: %i[show edit destroy]

    # GET /users
    def index
      params[:with_role] ||= true
      @users = User.includes(:roleable_clubs, :roleable_events)
      @users = @users.where.not(roles: { id: nil }) if params[:with_role] != 'false'
      @users = search @users
    end

    # GET /users/1
    def show; end

    # GET /users/new
    def new
      @user = User.new
    end

    # GET /users/1/edit
    def edit; end

    # POST /users
    def create
      @user = User.new(user_params)

      if @user.save
        redirect_to :root, notice: I18n.t('user.created')
      else
        render :new
      end
    end

    # PATCH/PUT /users/1
    def update
      if @user.update(user_params)
        flash[:notice] = I18n.t('user.updated')
        redirect_to_target_url
        redirect_to(:root) unless performed?
      else
        render :update_profile
      end
    end

    # DELETE /users/1
    def destroy
      @user.destroy
      redirect_to users_url, notice: 'User was successfully destroyed.'
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:first_name, :second_name, :last_name, :phone, :role, :email)
    end

    def search(scope)
      return scope if params[:search].blank?

      scope.where(
        '
          users.last_name ILIKE ?
          OR users.phone ILIKE ?
          OR users.email ILIKE ?
        ', "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%"
      )
    end

  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

module Users
  class ConfirmationsController < Devise::ConfirmationsController
    # GET /resource/confirmation/new
    # def new
    #   super
    # end

    # POST /resource/confirmation
    # def create
    #   super
    # end

    # GET /resource/confirmation?confirmation_token=abcdef
    # def show
    #   super
    # end

    # protected

    # The path used after resending confirmation instructions.
    # def after_resending_confirmation_instructions_path_for(resource_name)
    #   super(resource_name)
    # end

    # The path used after confirmation.
    # def after_confirmation_path_for(resource_name, resource)
    #   super(resource_name, resource)
    # end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    skip_before_action :verify_authenticity_token, only: :facebook
    skip_before_action :check_user_signed_in, :check_user_valid

    def google_oauth2
      oauth_action_for 'Google'
    end

    def facebook
      oauth_action_for 'Facebook'
    end

    def vkontakte
      oauth_action_for 'VK'
    end

    def failure
      redirect_to root_path
    end

    private

    def oauth_action_for(provider)
      if user.persisted?
        sign_in user, event: :authentication
        prepare_flash provider

        check_user_valid

        redirect_to_target_url unless performed?
        redirect_to(dogs_path) unless performed?
      else
        set_session
        redirect_to new_user_registration_url, alert: user_error_messages
      end
    end

    def prepare_flash(kind)
      set_flash_message(:notice, :success, kind: kind) if is_navigational_format?
    end

    def set_session
      # Removing extra as it can overflow some session stores
      session['devise.google_data'] = request.env['omniauth.auth'].except('extra')
    end

    def user_error_messages
      user.errors.full_messages.join("\n")
    end

    def user
      @user ||= User.from_omniauth(request.env['omniauth.auth'])
    end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

module Users
  class PasswordsController < Devise::PasswordsController
    # GET /resource/password/new
    # def new
    #   super
    # end

    # POST /resource/password
    # def create
    #   super
    # end

    # GET /resource/password/edit?reset_password_token=abcdef
    # def edit
    #   super
    # end

    # PUT /resource/password
    # def update
    #   super
    # end

    # protected

    # def after_resetting_password_path_for(resource)
    #   super(resource)
    # end

    # The path used after sending reset password instructions
    # def after_sending_reset_password_instructions_path_for(resource_name)
    #   super(resource_name)
    # end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

module Users
  class RegistrationsController < Devise::RegistrationsController
    # before_action :configure_sign_up_params, only: [:create]
    # before_action :configure_account_update_params, only: [:update]

    # GET /resource/sign_up
    # def new
    #   super
    # end

    # POST /resource
    # def create
    #   super
    # end

    # GET /resource/edit
    # def edit
    #   super
    # end

    # PUT /resource
    # def update
    #   super
    # end

    # DELETE /resource
    # def destroy
    #   super
    # end

    # GET /resource/cancel
    # Forces the session data which is usually expired after sign
    # in to be expired now. This is useful if the user wants to
    # cancel oauth signing in/up in the middle of the process,
    # removing all OAuth session data.
    # def cancel
    #   super
    # end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_up_params
    #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
    # end

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_account_update_params
    #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
    # end

    # The path used after sign up.
    # def after_sign_up_path_for(resource)
    #   super(resource)
    # end

    # The path used after sign up for inactive accounts.
    # def after_inactive_sign_up_path_for(resource)
    #   super(resource)
    # end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

module Users
  class SessionsController < Devise::SessionsController
    skip_before_action :check_user_valid, :check_user_signed_in

    # POST /resource/sign_in
    def create
      email_or_phone_params

      super
    end

    private

    def email_or_phone_params
      return if User.find_by(email: params[:user][:email]).present?
      return if phone_user.blank?

      params[:user][:email] = phone_user.email
    end

    def email_user
      @email_user ||= User.find_by(email: params[:user][:email])
    end

    def phone_user
      @phone_user ||= User.find_by(phone: formatted_phone(params[:user][:email]))
    end

    def formatted_phone(value)
      Phoner::Phone.parse(value).to_s
    rescue StandardError
      value
    end
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

module Users
  class UnlocksController < Devise::UnlocksController
    # GET /resource/unlock/new
    # def new
    #   super
    # end

    # POST /resource/unlock
    # def create
    #   super
    # end

    # GET /resource/unlock?unlock_token=abcdef
    # def show
    #   super
    # end

    # protected

    # The path used after sending unlock password instructions
    # def after_sending_unlock_instructions_path_for(resource)
    #   super(resource)
    # end

    # The path used after unlocking the resource
    # def after_unlock_path_for(resource)
    #   super(resource)
    # end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit destroy]
  before_action :set_user_for_update, only: %i[update]
  skip_before_action :check_user_valid, only: %i[edit update_profile update]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # GET /users/1/update_profile
  def update_profile
    @user = current_user
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to :root, notice: I18n.t('user.created')
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      flash[:notice] = I18n.t('user.updated')
      redirect_to_target_url
      redirect_to(:root) unless performed?
    else
      # render(referer_update_profile? ? :update_profile : :edit)
      render :update_profile
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  def facebook_user_deletion
    signed_request = params['signed_request']
    data = parse_fb_signed_request(signed_request)
    user = User.find_by(email: data['user_id'])
    user.destroy
    data = {
      url: "#{ENV['APP_HOST_URL']}/deletion_status?id=#{user.id}",
      confirmation_code: "del_#{user.id}"
    }
    render json: data
  end

  def deletion_status
    res = if User.find_by(uid: params[:id]).any?
        'User successfully deleted'
      else
        'User not deleted'
      end

    render text: res
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  def referer_update_profile?
    request.referer =~ %r{/update_profile$}
  end

  def set_user_for_update
    @user = referer_update_profile? ? @current_user : set_user
  end

  # Only allow a trusted parameter "white list" through.
  def user_params
    params.require(:user).permit(:first_name, :second_name, :last_name, :phone, :role, :email)
  end

  def parse_fb_signed_request(signed_request)
    encoded_sig, payload = signed_request.split('.', 2)
    secret = ENV['FACEBOOK_SECRET_ID']

    # Decode the data
    decoded_sig = Base64.urlsafe_decode64(encoded_sig)
    data = JSON.load(Base64.urlsafe_decode64(payload))

    # Create the HMAC signature
    expected_sig = OpenSSL::HMAC.digest("SHA256", secret, payload)

    if decoded_sig != expected_sig
      puts 'Bad Signed JSON signature!'
      return nil
    else
      data
    end
  end
end

app/views/admin/users/_form.html.slim
= form_for @user, html: { class: "form form-horizontal user" } do |f|
  .form-group
    = f.label :first_name, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :first_name, :class => 'form-control'
    = f.error_span(:first_name)
  .form-group
    = f.label :second_name, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :second_name, :class => 'form-control'
    = f.error_span(:second_name)
  .form-group
    = f.label :last_name, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :last_name, :class => 'form-control'
    = f.error_span(:last_name)
  .form-group
    = f.label :phone, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :phone, :class => 'form-control'
    = f.error_span(:phone)
  .form-group
    = f.label :role, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :role, :class => 'form-control'
    = f.error_span(:role)
  .form-group
    = f.label :email, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :email, :class => 'form-control'
    = f.error_span(:email)
  .form-group
    = f.label :encrypted_password, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :encrypted_password, :class => 'form-control'
    = f.error_span(:encrypted_password)
  .form-group
    = f.label :reset_password_token, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :reset_password_token, :class => 'form-control'
    = f.error_span(:reset_password_token)
  .form-group
    = f.label :reset_password_sent_at, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :reset_password_sent_at, :class => 'form-control'
    = f.error_span(:reset_password_sent_at)
  .form-group
    = f.label :remember_created_at, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :remember_created_at, :class => 'form-control'
    = f.error_span(:remember_created_at)
  .form-group
    = f.label :current_sign_in_at, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :current_sign_in_at, :class => 'form-control'
    = f.error_span(:current_sign_in_at)
  .form-group
    = f.label :last_sign_in_at, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :last_sign_in_at, :class => 'form-control'
    = f.error_span(:last_sign_in_at)
  .form-group
    = f.label :current_sign_in_ip, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :current_sign_in_ip, :class => 'form-control'
    = f.error_span(:current_sign_in_ip)
  .form-group
    = f.label :last_sign_in_ip, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :last_sign_in_ip, :class => 'form-control'
    = f.error_span(:last_sign_in_ip)
  .form-group
    = f.label :confirmation_token, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :confirmation_token, :class => 'form-control'
    = f.error_span(:confirmation_token)
  .form-group
    = f.label :confirmed_at, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :confirmed_at, :class => 'form-control'
    = f.error_span(:confirmed_at)
  .form-group
    = f.label :confirmation_sent_at, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :confirmation_sent_at, :class => 'form-control'
    = f.error_span(:confirmation_sent_at)
  .form-group
    = f.label :unconfirmed_email, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :unconfirmed_email, :class => 'form-control'
    = f.error_span(:unconfirmed_email)
  .form-group
    = f.label :failed_attempts, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :failed_attempts, :class => 'form-control'
    = f.error_span(:failed_attempts)
  .form-group
    = f.label :unlock_token, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :unlock_token, :class => 'form-control'
    = f.error_span(:unlock_token)
  .form-group
    = f.label :locked_at, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :locked_at, :class => 'form-control'
    = f.error_span(:locked_at)
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit t('save'), :class => 'btn btn-primary'
      '
      = link_to t('.cancel', :default => t("helpers.links.cancel")), users_path, :class => 'btn'

app/views/admin/users/edit.html.slim
- model_class = User
.page-header
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/admin/users/index.html.slim
- model_class = User
.page-header
  h1=t '.title'

form.d-flex action="" method="GET" id="search_form"
  .input-group
    .form-outline
      input.form-control type="search" name="search" value="#{params[:search]}"
    button.btn.btn-primary type="submit" for="search_form"
      i.bi.bi-search
  .form-check
    = hidden_field_tag :with_role, false
    = check_box_tag :with_role, true, params[:with_role] != 'false', class: 'form-check-input'
    label.form-check-label.text-nowrap
      = t '.with_role'

table.table.table-striped
  thead
    tr
      th= model_class.human_attribute_name(:first_name)
      th= model_class.human_attribute_name(:email)
      th= model_class.human_attribute_name(:phone)
      th= model_class.human_attribute_name(:role)
      th
  tbody
    - @users.each do |user|
      tr
        td
          = link_to edit_admin_user_path(user), class: 'm-1' do
            = user.fullname
        td= user.email
        td= user.phone
        td
          - user.roleable_clubs.each do |club|
            = club.name
            br
          - user.roleable_events.each do |event|
            = "#{l event.starts_on, format: :human} #{event.club.name} #{event.short_name}"
            br
        td.actions.text-center
          = link_to masquerade_path(user), class: 'm-1' do
            i.bi.bi-people-fill
          '
          - if false
            = link_to admin_user_path(user), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) } do
              i.bi.bi-trash-fill

app/views/admin/users/new.html.slim
- model_class = User
.page-header
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/admin/users/show.html.slim
- model_class = User
.page-header
  h1=t '.title', :default => model_class.model_name.human.titleize

p
  strong= model_class.human_attribute_name(:first_name) + ':'
  br
  = @user.first_name
p
  strong= model_class.human_attribute_name(:second_name) + ':'
  br
  = @user.second_name
p
  strong= model_class.human_attribute_name(:last_name) + ':'
  br
  = @user.last_name
p
  strong= model_class.human_attribute_name(:phone) + ':'
  br
  = @user.phone
p
  strong= model_class.human_attribute_name(:role) + ':'
  br
  = @user.role
p
  strong= model_class.human_attribute_name(:email) + ':'
  br
  = @user.email
p
  strong= model_class.human_attribute_name(:encrypted_password) + ':'
  br
  = @user.encrypted_password
p
  strong= model_class.human_attribute_name(:reset_password_token) + ':'
  br
  = @user.reset_password_token
p
  strong= model_class.human_attribute_name(:reset_password_sent_at) + ':'
  br
  = @user.reset_password_sent_at
p
  strong= model_class.human_attribute_name(:remember_created_at) + ':'
  br
  = @user.remember_created_at
p
  strong= model_class.human_attribute_name(:current_sign_in_at) + ':'
  br
  = @user.current_sign_in_at
p
  strong= model_class.human_attribute_name(:last_sign_in_at) + ':'
  br
  = @user.last_sign_in_at
p
  strong= model_class.human_attribute_name(:current_sign_in_ip) + ':'
  br
  = @user.current_sign_in_ip
p
  strong= model_class.human_attribute_name(:last_sign_in_ip) + ':'
  br
  = @user.last_sign_in_ip
p
  strong= model_class.human_attribute_name(:confirmation_token) + ':'
  br
  = @user.confirmation_token
p
  strong= model_class.human_attribute_name(:confirmed_at) + ':'
  br
  = @user.confirmed_at
p
  strong= model_class.human_attribute_name(:confirmation_sent_at) + ':'
  br
  = @user.confirmation_sent_at
p
  strong= model_class.human_attribute_name(:unconfirmed_email) + ':'
  br
  = @user.unconfirmed_email
p
  strong= model_class.human_attribute_name(:failed_attempts) + ':'
  br
  = @user.failed_attempts
p
  strong= model_class.human_attribute_name(:unlock_token) + ':'
  br
  = @user.unlock_token
p
  strong= model_class.human_attribute_name(:locked_at) + ':'
  br
  = @user.locked_at

= link_to t('.back', :default => t("helpers.links.back")), users_path, :class => 'btn btn-default'
'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(@user), :class => 'btn btn-default'
'
= link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(@user), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'